- .github/workflows/api.yml
- src/.dockerignore
- src/Dockerfile
- src/Oplog.Api/Program.cs
- src/Oplog.Api/SwaggerSetup.cs
> feat: initial radix setup

- src/Oplog.Api/Controllers/CommentsController.cs
- src/Oplog.Core/Commands/CreateCommentCommand.cs
- src/Oplog.Core/Commands/CreateCommentCommandHandler.cs
- src/Oplog.Core/Commands/UpdateCommentCommand.cs
- src/Oplog.Core/Commands/UpdateCommentCommandHandler.cs
- src/Oplog.Persistence/Models/Area.cs
- src/Oplog.Persistence/Models/Comment.cs
> feat: get user info

- src/Oplog.Api/Controllers/CommentsController.cs
- src/Oplog.Api/Controllers/ConfiguredTypesController.cs
- src/Oplog.Core/Enums/CategoryIdEnum.cs
- src/Oplog.Core/Oplog.Core.csproj
- src/Oplog.Core/Queries/ConfiguredTypesByCategory.cs
- src/Oplog.Core/Queries/ConfiguredTypesQueries.cs
- src/Oplog.Core/Queries/IConfiguredTypesQueries.cs
- src/Oplog.Persistence/Models/Category.cs
- src/Oplog.Persistence/OplogDbContext.cs
- src/Oplog.Persistence/Repositories/ConfiguredTypesRepository.cs
- src/Oplog.Persistence/Repositories/IConfiguredTypesRepository.cs
> feat: configured types endpoints

- src/Oplog.Api/Controllers/AreasController.cs
- src/Oplog.Api/Controllers/ConfiguredTypesController.cs
- src/Oplog.Core/Queries/AreasQueries.cs
- src/Oplog.Core/Queries/ConfiguredTypesByCategoryResult.cs
- src/Oplog.Core/Queries/ConfiguredTypesQueries.cs
- src/Oplog.Core/Queries/GetAllAreasResult.cs
- src/Oplog.Core/Queries/IAreasQueries.cs
- src/Oplog.Core/Queries/IConfiguredTypesQueries.cs
- src/Oplog.Persistence/OplogDbContext.cs
- src/Oplog.Persistence/Repositories/AreasRepository.cs
- src/Oplog.Persistence/Repositories/IAreasRepository.cs
- src/Oplog.sln
> feat: areas endpoints

- src/Oplog.Api/Controllers/OperationAreasController.cs
- src/Oplog.Api/Program.cs
- src/Oplog.Core/Queries/IOperationAreasQueries.cs
- src/Oplog.Core/Queries/OperationAreasQueries.cs
- src/Oplog.Persistence/Migrations/20230420092322_DropAreaTable.Designer.cs
- src/Oplog.Persistence/Migrations/20230420092322_DropAreaTable.cs
- src/Oplog.Persistence/Models/OperationArea.cs
- src/Oplog.Persistence/OplogDbContext.cs
- src/Oplog.Persistence/Repositories/IOperationsAreasRepository.cs
- src/Oplog.Persistence/Repositories/OperationAreasRepository.cs
Added OperationArea table with non identity increment specification.
> feat: remove area table and add non identity specification

- src/Oplog.Persistence/Repositories/LogsRepository.cs
I've also manually created an Index for CreatedDate in db
-CREATE INDEX idx_CreatedDate ON Logs(CreatedDate);
> implemented order of CreatedDate - to make us of index

- src/Oplog.Api/Controllers/UserDefinedFilterController.cs
- src/Oplog.Core/Commands/DeleteUserDefinedFilterCommand.cs
- src/Oplog.Core/Commands/DeleteUserDefinedFilterCommandHandler.cs
- src/Oplog.Persistence/Repositories/IUserDefinedFilterRepository.cs
- src/Oplog.Persistence/Repositories/UserDefinedFilterRepository.cs
> feat: delete user defined filter

- src/Oplog.Api/Controllers/LogTemplateController.cs
- src/Oplog.Api/Models/CreateLogTemplateRequest.cs
- src/Oplog.Api/Program.cs
- src/Oplog.Core/Commands/CreateLogTemplateCommand.cs
- src/Oplog.Core/Commands/CreateLogTemplateCommandHandler.cs
- src/Oplog.Core/Commands/DeleteLogTemplateCommand.cs
- src/Oplog.Core/Commands/DeleteLogTemplateCommandHandler.cs
- src/Oplog.Core/Queries/GetAllLogTemplateResult.cs
- src/Oplog.Core/Queries/ILogTemplateQueries.cs
- src/Oplog.Core/Queries/LogTemplateQueries.cs
- src/Oplog.Persistence/Migrations/20230531081345_AddLogTemplates.Designer.cs
- src/Oplog.Persistence/Migrations/20230531081345_AddLogTemplates.cs
- src/Oplog.Persistence/Models/LogTemplate.cs
- src/Oplog.Persistence/OplogDbContext.cs
- src/Oplog.Persistence/Repositories/ILogTemplateRepository.cs
- src/Oplog.Persistence/Repositories/LogTemplateRepository.cs
- src/Oplog.Persistence/Repositories/UserDefinedFilterRepository.cs
> feat: log templates

- src/Oplog.Core/Queries/GetUserDefinedFiltersByCreatedUserResult.cs
- src/Oplog.Core/Queries/UserDefinedFilterQueries.cs
- src/Oplog.Persistence/Repositories/ConfiguredTypesRepository.cs
- src/Oplog.Persistence/Repositories/IConfiguredTypesRepository.cs
- src/Oplog.Persistence/Repositories/IOperationsAreasRepository.cs
- src/Oplog.Persistence/Repositories/OperationAreasRepository.cs
> feat: return filter name

- src/Oplog.Api/Oplog.Api.csproj
- src/Oplog.Api/Program.cs
> fix: datetime utc

- src/Oplog.Core/Queries/GetAllLogTemplateResult.cs
> fix: author typo

- src/Oplog.Api/Controllers/LogsController.cs
- src/Oplog.Api/Models/CreateCustomFilterRequest.cs
- src/Oplog.Api/Models/CreateLogRequest.cs
- src/Oplog.Api/Models/CreateLogTemplateRequest.cs
- src/Oplog.Api/Models/GetFilteredLogsRequest.cs
- src/Oplog.Api/Models/UpdateLogRequest.cs
- src/Oplog.Api/ValidationAttributes/ValidateFilterItems.cs
> feat: add model vallidation

- src/Oplog.Api/Controllers/OperationAreasController.cs
- src/Oplog.Core/Queries/IOperationAreasQueries.cs
- src/Oplog.Core/Queries/OperationAreasQueries.cs
- src/Oplog.Persistence/Migrations/20230726072829_AddIsActiveFieldForArea.Designer.cs
- src/Oplog.Persistence/Migrations/20230726072829_AddIsActiveFieldForArea.cs
- src/Oplog.Persistence/Models/OperationArea.cs
- src/Oplog.Persistence/Repositories/IOperationsAreasRepository.cs
- src/Oplog.Persistence/Repositories/OperationAreasRepository.cs
> feat: only return active areas

- src/Oplog.Api/Controllers/LogsController.cs
- src/Oplog.Core/Commands/CreateLogCommandHandler.cs
- src/Oplog.Core/Commands/UpdateLogCommandHandler.cs
- src/Oplog.Core/Commands/UpdateLogResult.cs
- src/Oplog.IntegrationTests/Tests/CreateCustomFilterCommandTests.cs
- src/Oplog.IntegrationTests/Tests/CreateLogCommandTests.cs
> test: more integration tests

- src/Oplog.Api/Controllers/ConfiguredTypesController.cs
- src/Oplog.Core/Queries/ConfiguredTypesQueries.cs
- src/Oplog.Core/Queries/IConfiguredTypesQueries.cs
- src/Oplog.Persistence/Migrations/20230726080919_AddIsActiveFieldToConfiguredTypes.Designer.cs
- src/Oplog.Persistence/Migrations/20230726080919_AddIsActiveFieldToConfiguredTypes.cs
- src/Oplog.Persistence/Models/ConfiguredType.cs
- src/Oplog.Persistence/Repositories/ConfiguredTypesRepository.cs
- src/Oplog.Persistence/Repositories/IConfiguredTypesRepository.cs
> feat: only get active types

- src/Oplog.Api/Program.cs
> fix: add use hsts

- src/Oplog.Core/Commands/LogTemplates/CreateLogTemplateCommandHandler.cs
- src/Oplog.Core/Commands/LogTemplates/CreateLogTemplateResult.cs
- src/Oplog.Core/Commands/LogTemplates/DeleteLogTemplateCommandHandler.cs
- src/Oplog.Core/Commands/Logs/DeleteLogsCommandHandler.cs
- src/Oplog.Core/Commands/Logs/DeleteLogsResult.cs
- src/Oplog.Core/Commands/Logs/UpdateLogResult.cs
- src/Oplog.IntegrationTests/Tests/LogTemplates/DeleteLogTemplateCommandTests.cs
- src/Oplog.IntegrationTests/Tests/Logs/DeleteLogsComandTests.cs
- src/Oplog.IntegrationTests/Tests/Logs/UpdateLogCommandTests.cs
- src/Oplog.Persistence/Repositories/ILogTemplateRepository.cs
- src/Oplog.Persistence/Repositories/LogTemplateRepository.cs
adding integration more integration tests for logs, log templates and filters
> test: adding more integration tests

- src/Oplog.Api/Controllers/CustomFilterController.cs
- src/Oplog.Api/Controllers/LogTemplateController.cs
- src/Oplog.Api/Controllers/LogsController.cs
- src/Oplog.Api/Oplog.Api.csproj
- src/Oplog.Api/Program.cs
- src/Oplog.IntegrationTests/Oplog.IntegrationTests.csproj
- src/Oplog.Persistence/Oplog.Persistence.csproj
update packages and some code refactor
> chore: update packages

- src/Oplog.Api/SwaggerSetup.cs
> chore: remove swagger scopes

- src/Oplog.Persistence/Migrations/20230818100820_ChangeOrderByInSp.Designer.cs
- src/Oplog.Persistence/Migrations/20230818100820_ChangeOrderByInSp.cs
> feat: change sort order

- src/Oplog.Api/Controllers/CustomFilterController.cs
- src/Oplog.Api/Controllers/LogTemplateController.cs
> fix: update delete urls

- src/Oplog.Api/Controllers/LogsController.cs
- src/Oplog.Api/Models/GetSearchLogsRequest.cs
- src/Oplog.Core/AzureSearch/IIndexSearchClient.cs
- src/Oplog.Core/AzureSearch/IndexDocumentClient.cs
- src/Oplog.Core/AzureSearch/IndexSearchClient.cs
- src/Oplog.Core/AzureSearch/SearchOptionsBuilder.cs
- src/Oplog.Core/AzureSearch/SearchRequest.cs
- src/Oplog.Core/Events/Logs/LogUpdatedEvent.cs
- src/Oplog.Core/Events/Logs/LogUpdatedEventHandler.cs
- src/Oplog.Core/Events/Logs/LogsDeletedEvent.cs
- src/Oplog.Core/Events/Logs/LogsDeletedEventHandler.cs
- src/Oplog.Core/Queries/Logs/LogsQueries.cs
- src/Oplog.Core/Queries/Logs/SearchLogsQueries.cs
azure cognitive search text search
> feat: text search

- src/Oplog.Core/AzureSearch/IndexSearchClient.cs
- src/Oplog.Core/AzureSearch/SearchOptionsBuilder.cs
> feat: add log type filter

- src/Oplog.Core/AzureSearch/SearchOptionsBuilder.cs
> feat: adding more filters

- src/Oplog.Core/Commands/Logs/CreateLogCommandHandler.cs
- src/Oplog.Core/Commands/Logs/CreateLogResult.cs
wait for the create result from cognitive search
> fix: wait for the result to come back

- src/Oplog.Core/AzureSearch/IndexDocumentClient.cs
- src/Oplog.Core/Commands/Logs/DeleteLogsCommandHandler.cs
- src/Oplog.Core/Commands/Logs/DeleteLogsResult.cs
- src/Oplog.IntegrationTests/Tests/Logs/DeleteLogsComandTests.cs
delete cognitive search records
> feat: delete cognitive search records

- src/Oplog.Core/AzureSearch/IndexDocumentClient.cs
- src/Oplog.Core/Commands/Logs/DeleteLogsCommandHandler.cs
bring delete delay one method up and change value
> feat: update delete delay

- src/Oplog.Persistence/Migrations/20230912082418_AddRowVersionInLogTable.Designer.cs
- src/Oplog.Persistence/Migrations/20230912082418_AddRowVersionInLogTable.cs
- src/Oplog.Persistence/Migrations/20230912083000_AddRowVersionColumnToLogsView.Designer.cs
- src/Oplog.Persistence/Migrations/20230912083000_AddRowVersionColumnToLogsView.cs
- src/Oplog.Persistence/Models/Log.cs
- src/Oplog.Persistence/OplogDbContext.cs
add row version to the log table
> feat: add row version

- src/Oplog.Core/AzureSearch/SearchOptionsBuilder.cs
update date selection to effective time
> feat: update date selection

- src/Oplog.Api/Program.cs
db migrate command execution time out fix
> feat: db migrate execution timeout

- src/Oplog.Api/Program.cs
> feat: remove the execution timeout

- CONTRIBUTING.md
- SECURITY.md
adding contributing and security files
> chore: adding contributing and security files

- src/Oplog.Api/Program.cs
disable app insights active sampling
> fix: disable app insights active sampling

- src/Oplog.Core/Queries/Logs/SearchLogsQueries.cs
> fix: page count bug

- radixconfig.yaml
workload identity config changes
> feat: workload identity config changes

- src/Oplog.Api/Oplog.Api.csproj
- src/Oplog.Api/Program.cs
workload identity code changes
> feat: workload identity code changes

- radixconfig.yaml
> feat: workload identity prod

- src/Oplog.Core/AzureSearch/SearchOptionsBuilder.cs
the search accepts multiple terms as search text seperated by space char
> feat: improve search

- src/Oplog.Core/AzureSearch/SearchOptionsBuilder.cs
> fix: multiple keyword search

- src/Oplog.Core/AzureSearch/SearchOptionsBuilder.cs
> feat: add escape chars

- src/Oplog.Core/AzureSearch/SearchOptionsBuilder.cs
> fix: add escaping chars

- radixconfig.yaml
> chore: add usebuildkit option

- src/Oplog.Core/AzureSearch/SearchOptionsBuilder.cs
remove extra search conditions
> fix: remove extra search conditions

- src/Oplog.Core/AzureSearch/SearchOptionsBuilder.cs
feat: implemented special character search
#160
> feat: implemented special character search

- src/Oplog.Api/Oplog.Api.csproj
- src/Oplog.Api/Program.cs
> feat: add open telemetry

- radixconfig.yaml
Got OutOfMemoryException in dev. Increase limits to allow for more memory.
Linked to #170
> chore: adjust radix resources

- .github/workflows/api.yml
- src/Oplog.Api/Controllers/LogsController.cs
- src/Oplog.Api/Models/GetSearchLogsRequest.cs
- src/Oplog.Core/AzureSearch/IndexSearchClient.cs
- src/Oplog.Core/AzureSearch/SearchOptionsBuilder.cs
- src/Oplog.Core/AzureSearch/SearchRequest.cs
- src/Oplog.IntegrationTests/Oplog.IntegrationTests.csproj
- src/Oplog.IntegrationTests/TestRunSetUp.cs
feat: add option to hide visible to all
#8
> feat: add option to hide visible to all

- radixconfig.yaml
#173 Increse the cpu limit in production
> chore: adjust cpu limit in prod
